#!/usr/bin/env bash

set -e

kompile lambda.k

check_output() {
    local expected="$1"; shift
    diff -u --label expected "$expected" \
            --label actual   -
}

for f in t/*.lambda; do
    echo "$f"
    kast "$f" | check_output "$f.kast"
    krun "$f" | check_output "$f.krun"
done
