#!/usr/bin/env bash
set -e

BASE=$(cd $(dirname "$0") && pwd -P)

cd "$BASE"
[ -e bats/bin/bats ] || {
    echo >&2 'Did not find bats executable. `git submodule update --init`?'
    exit 1
}
tests=( $(find "$@" -name bats          -prune \
                 -o -name test_helper   -prune \
                 -o -name .git          -prune \
                 -o -name '*.bats'      -print) )
bats/bin/bats "${tests[@]}"
